amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAIUTHVMI6HCUMY7GA
  secretKey: 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
  bucketName: p-alpha
  expirationDate: 2019-12-30T12:00:00.000Z
  acl: public-read
  serverSideEncryption: AES256
  amzAlgorithm: AWS4-HMAC-SHA256
  region: us-east-2